(function(){
 const body=document.body,page=body.dataset.page||'events';
 const search=page==='events'?'<button class="header-search-toggle" id="searchToggle" aria-label="Hledat"><i class="fas fa-search"></i></button><div class="header-search" id="headerSearch"><input id="search" type="search" placeholder="Hledat akci nebo místo…" autocomplete="off"><button id="searchClear" aria-label="Smazat hledání"><i class="fas fa-times"></i></button></div>':'';
 const nav='<nav class="main-nav"><a href="/" data-nav="events">Akce</a><a href="/kalendar" data-nav="calendar">Kalendář</a><a href="/pridat" data-nav="add">Přidat akci</a><a href="/o-projektu" data-nav="about">O projektu</a></nav>';
 const header='<header class="topbar"><div class="brand"><a class="brand-home" href="/"><img src="/assets/metrobus-symbol.svg" alt=""><span class="brand-copy"><span>ŠOTOUŠŮV KALENDÁŘ</span></span></a><a class="brand-metrobus" href="https://metrobus.cz/" target="_blank" rel="noopener">METROBUS</a></div>'+search+nav+'</header>';
 const footer='<footer class="site-footer'+(page==='events'?' feed-footer':'')+'"><div class="footer-fun">Konečná! Prosíme, vystupte.</div><div class="footer-brand"><a href="https://metrobus.cz/" target="_blank" rel="noopener">Metrobus</a> · <span class="footer-year">2026</span></div><div class="footer-links"><a href="/o-projektu#kontakt">Kontakt</a><a href="/admin">Administrace</a></div></footer>';
 const mobile='<nav class="mobile-nav" aria-label="Hlavní navigace"><a href="/" data-nav="events"><i class="fas fa-list"></i><span>Akce</span></a><a href="/kalendar" data-nav="calendar"><i class="fas fa-calendar-alt"></i><span>Kalendář</span></a><a href="/pridat" data-nav="add"><i class="fas fa-plus-circle"></i><span>Přidat</span></a><a href="/o-projektu" data-nav="about"><i class="fas fa-info-circle"></i><span>O projektu</span></a></nav>';
 const top=document.querySelector('[data-layout="header"]'),bottom=document.querySelector('[data-layout="footer"]');if(top)top.outerHTML=header;if(bottom)bottom.outerHTML=footer;if(!document.querySelector('.mobile-nav'))document.body.insertAdjacentHTML('beforeend',mobile);
 document.querySelectorAll('.main-nav a,.mobile-nav a').forEach(a=>{const target=a.dataset.nav;const active=target===page||(page==='detail'&&target==='events');if(active){a.classList.add('active');a.setAttribute('aria-current','page')}});
 if(page==='detail'){
   const pathId=location.pathname.match(/\/akce\/([0-9]+)\/?$/)?.[1];const queryId=new URLSearchParams(location.search).get('id');const id=pathId||queryId;
   fetch('/api/auth.php',{credentials:'same-origin'}).then(r=>r.ok?r.json():null).then(data=>{if(data?.user&&id&&!document.querySelector('.editor-shortcut'))document.body.insertAdjacentHTML('beforeend','<a class="editor-shortcut" href="/admin?event='+encodeURIComponent(id)+'"><i class="fas fa-pen"></i><span>Upravit akci</span></a>')}).catch(()=>{});
 }
})();
