const $=s=>document.querySelector(s),esc=SK.escapeHtml;
let adminView='all',events=[],proposals=[],requested=new URLSearchParams(location.search).get('event');
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.error||'api_error'),{status:r.status,data});return data}
const sid=v=>String(v??''),firstDate=e=>(e.dates&&e.dates[0])||{};
const displayDate=e=>{const d=firstDate(e);if(!d.starts_on)return'Bez data';return d.starts_on+((e.dates?.length||0)>1?' +'+(e.dates.length-1):'')};
const displayPlace=e=>[e.city,e.place].filter(Boolean).join(' · ')||e.region||'—';
async function loadSession(){try{const{user}=await api('/api/auth.php');renderSession(user)}catch{renderSession(null)}}
function renderSession(user){$('#adminLogin').hidden=!!user;$('#adminApp').hidden=!user;if(user){$('#adminUser').textContent=user.display_name||user.email;loadAll()}}
$('#adminLoginForm').onsubmit=async e=>{e.preventDefault();$('#adminLoginError').hidden=true;const f=e.currentTarget;try{const{user}=await api('/api/auth.php',{method:'POST',body:JSON.stringify({email:f.email.value.trim(),password:f.password.value})});f.reset();renderSession(user)}catch{$('#adminLoginError').hidden=false}};
$('#adminLogout').onclick=async()=>{await api('/api/auth.php',{method:'DELETE'});events=[];proposals=[];renderSession(null)};
async function loadAll(){const [{events:list,pending_proposals},{proposals:p}]=await Promise.all([api('/api/admin/events.php'),api('/api/admin/proposals.php')]);events=list;proposals=p;$('#proposalCount').textContent=pending_proposals?'('+pending_proposals+')':'';renderView();if(requested){const id=requested;requested=null;openEditor(id)}}
function renderView(){const proposalMode=adminView==='proposals';$('#eventsPane').hidden=proposalMode;$('#proposalsPane').hidden=!proposalMode;proposalMode?renderProposals():renderList()}
function renderList(){const q=$('#adminSearch').value.trim().toLowerCase();const filtered=events.filter(e=>{const hay=[e.id,e.title,e.city,e.place,e.region].join(' ').toLowerCase();const ok=adminView==='all'||(adminView==='review'&&e.review_status==='automatic')||(adminView==='cancelled'&&e.status==='cancelled')||(adminView==='hidden'&&e.status==='hidden');return(!q||hay.includes(q))&&ok});$('#adminCount').textContent='('+events.length+')';const rc=events.filter(e=>e.review_status==='automatic').length;$('#reviewCount').textContent=rc?'('+rc+')':'';$('#adminList').innerHTML=filtered.length?filtered.map(e=>{const cats=(e.categories||[]).map(id=>(SK.CATEGORY_BY_ID[id]||SK.CATEGORY_BY_ID.other).label).join(', ');return'<button class="admin-row" data-id="'+esc(sid(e.id))+'"><div class="admin-row-main"><small>#'+esc(sid(e.id))+' · '+esc(displayDate(e))+'</small><strong>'+esc(SK.stripEmoji(e.title))+'</strong><span class="admin-row-mobilemeta">'+esc(displayPlace(e))+' · '+esc(cats)+'</span></div><span class="admin-cell admin-place">'+esc(displayPlace(e))+'</span><span class="admin-cell admin-cats">'+esc(cats)+'</span><span class="admin-cell"><span class="admin-status '+esc(e.status)+'">'+({active:'Aktivní',cancelled:'Zrušená',hidden:'Skrytá'}[e.status]||e.status)+'</span></span><span class="admin-cell"><span class="admin-review '+esc(e.review_status)+'"><i class="fas '+(e.review_status==='human_reviewed'?'fa-user-check':'fa-robot')+'"></i>'+(e.review_status==='human_reviewed'?'Zkontrolovaná':'Robot')+'</span></span></button>'}).join(''):'<div class="admin-empty">Žádné akce.</div>';document.querySelectorAll('.admin-row').forEach(b=>b.onclick=()=>openEditor(b.dataset.id))}
function renderProposals(){const q=$('#adminSearch').value.trim().toLowerCase();const list=proposals.filter(p=>!q||[p.event_id,p.title].join(' ').toLowerCase().includes(q));$('#proposalList').innerHTML=list.length?list.map(p=>'<article class="admin-proposal '+esc(p.severity)+'"><div><small>#'+esc(sid(p.event_id))+' · '+esc(p.severity==='important'?'DŮLEŽITÁ ZMĚNA':'NÁVRH ZMĚNY')+'</small><h3>'+esc(p.title)+'</h3>'+Object.entries(p.changes||{}).map(([k,v])=>'<div class="proposal-change"><strong>'+esc(k)+'</strong><span>'+esc(JSON.stringify(v.current))+'</span><i class="fas fa-arrow-right"></i><span>'+esc(JSON.stringify(v.proposed))+'</span></div>').join('')+'</div><div class="proposal-actions"><button data-reject="'+p.id+'" class="admin-quiet">Odmítnout</button><button data-accept="'+p.id+'" class="admin-primary">Přijmout</button></div></article>').join(''):'<div class="admin-empty">Žádné návrhy změn.</div>';document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>resolveProposal(b.dataset.accept,'accept'));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>resolveProposal(b.dataset.reject,'reject'))}
async function resolveProposal(id,action){await api('/api/admin/proposals.php',{method:'POST',body:JSON.stringify({id:Number(id),action})});await loadAll()}
$('#adminSearch').addEventListener('input',renderView);document.querySelectorAll('#adminTabs button').forEach(b=>b.onclick=()=>{adminView=b.dataset.view;document.querySelectorAll('#adminTabs button').forEach(x=>x.classList.toggle('active',x===b));renderView()});
$('#editorCategories').innerHTML=SK.CATEGORY_DEFS.map(c=>'<label class="admin-category category-'+c.id+'"><input type="checkbox" name="categories" value="'+c.id+'"><span><i class="fas '+c.icon+'"></i>'+c.label+'</span></label>').join('');
function dateRow(d={}){return'<div class="admin-date-row"><input type="date" data-start value="'+esc(d.starts_on||'')+'"><span>–</span><input type="date" data-end value="'+esc(d.ends_on||d.starts_on||'')+'"><button type="button" data-remove-date class="admin-icon" aria-label="Odebrat termín"><i class="fas fa-times"></i></button></div>'}
function bindDateRemovers(){document.querySelectorAll('[data-remove-date]').forEach(b=>b.onclick=()=>{b.closest('.admin-date-row').remove();if(!$('#editorDates').children.length){$('#editorDates').insertAdjacentHTML('beforeend',dateRow());bindDateRemovers()}})}
function renderDates(ds=[]){$('#editorDates').innerHTML=(ds.length?ds:[{}]).map(dateRow).join('');bindDateRemovers()}
$('#addDate').onclick=()=>{$('#editorDates').insertAdjacentHTML('beforeend',dateRow());bindDateRemovers()};
function fillEditor(e,newMode=false){const f=$('#editorForm');f.dataset.new=newMode?'1':'0';f.elements.id.value=e?.id||'';f.elements.title.value=e?.title||'';f.elements.time.value=(e?.time_start||firstDate(e||{}).starts_at||'').slice(0,5);f.elements.endTime.value=(e?.time_end||firstDate(e||{}).ends_at||'').slice(0,5);f.elements.allDay.checked=e?Number(e.all_day)!==0:true;for(const k of ['city','place','region','country','route','organizer','description'])f.elements[k].value=e?.[k]||'';f.elements.source.value=(e?.sources?.find(s=>Number(s.is_primary))?.url)||e?.sources?.[0]?.url||e?.public_url||'';f.elements.editorState.value=e?.status||'active';f.elements.reviewStatus.value=e?.review_status||'human_reviewed';f.querySelectorAll('[name="categories"]').forEach(x=>x.checked=(e?.categories||[]).includes(x.value));renderDates(e?.dates||[]);$('#editorTitle').textContent=newMode?'Nová akce':SK.stripEmoji(e.title);$('#editorId').textContent=newMode?'':'#'+e.id;$('#editorPublicLink').hidden=newMode;$('#editorPublicLink').href=newMode?'#':'/akce/'+encodeURIComponent(e.id);$('#adminEditor').hidden=false;document.body.classList.add('admin-modal-open')}
function openEditor(id){const e=events.find(x=>sid(x.id)===sid(id));if(e)fillEditor(e,false)}
$('#newEvent').onclick=()=>fillEditor(null,true);function closeEditor(){$('#adminEditor').hidden=true;document.body.classList.remove('admin-modal-open')}$('#editorClose').onclick=closeEditor;$('#adminEditor').onclick=e=>{if(e.target===$('#adminEditor'))closeEditor()};$('#markReviewed').onclick=()=>{$('#editorForm').elements.reviewStatus.value='human_reviewed'};
$('#editorForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value;const dates=[...document.querySelectorAll('.admin-date-row')].map(r=>({starts_on:r.querySelector('[data-start]').value,ends_on:r.querySelector('[data-end]').value||r.querySelector('[data-start]').value,starts_at:f.elements.time.value||null,ends_at:f.elements.endTime.value||null})).filter(d=>d.starts_on);const payload={title:f.elements.title.value.trim(),description:f.elements.description.value.trim()||null,city:f.elements.city.value.trim()||null,place:f.elements.place.value.trim()||null,region:f.elements.region.value.trim()||null,country:f.elements.country.value.trim()||null,route:f.elements.route.value.trim()||null,organizer:f.elements.organizer.value.trim()||null,time_start:f.elements.time.value||null,time_end:f.elements.endTime.value||null,all_day:f.elements.allDay.checked,public_url:f.elements.source.value.trim()||null,status:f.elements.editorState.value,review_status:f.elements.reviewStatus.value,categories:[...f.querySelectorAll('[name="categories"]:checked')].map(x=>x.value),dates};try{if(f.dataset.new==='1')await api('/api/admin/events.php',{method:'POST',body:JSON.stringify(payload)});else await api('/api/admin/event.php?id='+encodeURIComponent(id),{method:'PUT',body:JSON.stringify(payload)});closeEditor();await loadAll()}catch{alert('Uložení se nepodařilo. Zkus to znovu.')}};
loadSession();
