const $=s=>document.querySelector(s),esc=SK.escapeHtml,{CATEGORY_DEFS,CATEGORY_BY_ID}=SK;
let events=[],visibleDayCount=12;const selectedCategories=new Set(),selectedRegions=new Set();
const iso=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),today=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
const fmt=d=>d.toLocaleDateString('cs-CZ',{day:'numeric',month:'long',year:'numeric'}),weekday=d=>d.toLocaleDateString('cs-CZ',{weekday:'long'});
const categoryHtml=e=>(e.categories||[]).map(id=>{const c=CATEGORY_BY_ID[id]||CATEGORY_BY_ID.other;return'<span class="category category-'+id+'"><i class="fas '+c.icon+'"></i>'+c.label+'</span>'}).join('');
const loc=e=>[e.city,e.place].filter(Boolean).join(' · ')||e.region||'';
function eachDay(a,b){const out=[],d=new Date(a+'T00:00:00'),end=new Date((b||a)+'T00:00:00');while(d<=end){out.push(new Date(d));d.setDate(d.getDate()+1)}return out}
function occurrenceGroups(list){const groups=new Map(),t=today();for(const e of list)for(const term of(e.dates||[]))for(const d of eachDay(term.starts_on,term.ends_on)){if(d<t)continue;const k=iso(d);if(!groups.has(k))groups.set(k,{date:d,events:[]});if(!groups.get(k).events.some(x=>String(x.id)===String(e.id)))groups.get(k).events.push(e)}return[...groups.values()].sort((a,b)=>a.date-b.date)}
function match(e,q){const hay=[e.id,e.title,e.city,e.place,e.region,e.route].join(' ').toLowerCase();const catOk=!selectedCategories.size||(e.categories||[]).some(c=>selectedCategories.has(c));const regs=String(e.region||'').split('/').map(x=>x.trim());const regOk=!selectedRegions.size||regs.some(r=>selectedRegions.has(r));return(!q||hay.includes(q))&&catOk&&regOk}
function card(e){return'<a class="event" href="'+SK_RUNTIME.url('/akce/?id='+encodeURIComponent(e.id))+'"><div class="event-main"><h2>'+esc(SK.stripEmoji(e.title))+'</h2><div class="event-info"><div class="categories">'+categoryHtml(e)+'</div>'+(loc(e)?'<div class="location-meta"><i class="fas fa-map-marker-alt"></i><span>'+esc(loc(e))+'</span></div>':'')+'</div></div></a>'}
function render(){const q=$('#search').value.trim().toLowerCase(),groups=occurrenceGroups(events.filter(e=>match(e,q))),shown=groups.slice(0,visibleDayCount);$('#events').innerHTML=shown.map(g=>'<section class="day"><div class="date"><div class="date-label"><strong>'+fmt(g.date)+'</strong><span>'+weekday(g.date)+'</span></div></div><div class="cards">'+g.events.map(card).join('')+'</div></section>').join('')+(shown.length<groups.length?'<button class="lazy-loader" id="loadMore"><span>Načíst další dny</span></button>':'')||'<div class="empty-state"><i class="fas fa-calendar-times"></i><strong>Žádné akce neodpovídají filtru.</strong></div>';document.body.classList.toggle('feed-complete',shown.length>=groups.length);$('#loadMore')?.addEventListener('click',()=>{visibleDayCount+=12;render()})}
function buildFilters(){const regions=[...new Set(events.flatMap(e=>String(e.region||'').split('/').map(x=>x.trim())).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'cs'));$('#categoryFilter').innerHTML=CATEGORY_DEFS.map(c=>'<button type="button" class="filter-chip category-'+c.id+'" data-category="'+c.id+'"><i class="fas '+c.icon+'"></i><span>'+c.label+'</span></button>').join('');$('#regionPicker').innerHTML=regions.map(r=>'<button type="button" class="region-option" data-region="'+esc(r)+'"><span class="modern-check"><i class="fas fa-check"></i></span><span>'+esc(r)+'</span></button>').join('');document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{selectedCategories.has(b.dataset.category)?selectedCategories.delete(b.dataset.category):selectedCategories.add(b.dataset.category);b.classList.toggle('active');visibleDayCount=12;render()});document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{selectedRegions.has(b.dataset.region)?selectedRegions.delete(b.dataset.region):selectedRegions.add(b.dataset.region);b.classList.toggle('active');visibleDayCount=12;render()})}
$('#regionTrigger').onclick=()=>$('#regionPicker').classList.toggle('open');$('#clearFilters').onclick=()=>{selectedCategories.clear();selectedRegions.clear();buildFilters();render()};$('#filterToggle').onclick=()=>{const f=$('#filterbar'),open=f.classList.toggle('open');f.classList.toggle('collapsed',!open)};$('#search').addEventListener('input',()=>{visibleDayCount=12;render()});$('#searchToggle').onclick=()=>{document.body.classList.add('search-open');$('#search').focus()};$('#searchClear').onclick=()=>{if($('#search').value){$('#search').value='';render()}else document.body.classList.remove('search-open')};
(async()=>{try{events=await SK_RUNTIME.events({from:iso(today()),status:'active'});buildFilters();render()}catch{$('#events').innerHTML='<div class="empty-state"><strong>Akce se nepodařilo načíst.</strong></div>'}})();
