window.EVENTS=[
  {
    "id": "DA-20260926-DPP-RTO-CHUCHLE",
    "title": "Autobusem RTO na dostihy do Chuchle",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "11:00",
    "endTime": "",
    "place": "Karlovo náměstí – dostihové závodiště Chuchle",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Karlovo náměstí – Velká Chuchle",
    "transport": "autobus",
    "type": "nostalgická jízda",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Historický autobus Škoda 706 RTO vyjede 26. 9. 2026 z Karlova náměstí na dostihové závodiště ve Velké Chuchli při příležitosti 120 let chuchelského závodiště. DPP nově zveřejnil dva odjezdy, v 11:00 a 12:00. Jízda trvá přibližně 15–20 minut a stojí 250 Kč; v ceně je místenka s jízdenkou na autobus, voucher na dostihový program a welcome drink, nikoli vstupenka na závodiště.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-MLADEJOV-DEN-ZELEZNICE",
    "title": "Den (mladějovské) železnice 2026",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Mladějovská průmyslová dráha / Průmyslové muzeum Mladějov",
    "city": "Mladějov na Moravě",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "",
    "transport": "železnice / úzkokolejka",
    "type": "den železnice / muzejní akce / nostalgická jízda",
    "organizer": "Mladějovská průmyslová dráha / Průmyslové muzeum Mladějov",
    "description": "Poslední provozní den mladějovské úzkokolejky v sezóně 2026 s doprovodným programem; hlavní část má začít kolem 12:00. Podrobný program a zvláštní jízdní řád pro rok 2026 pořadatel zatím připravuje.",
    "source": "https://www.mladejov.cz/den-zeleznice",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "he14i4vb4tls4bp7udn0cqr3k4",
    "title": "Praha: Pražské tunely a mosty",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Praha",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Praha",
    "transport": "železnice",
    "type": "zvláštní jízda",
    "organizer": "Valenta Rail",
    "description": "Spanilá jízda motorového rychlíku Prahou. Průjezd nákladními tratěmi bez pravidelné osobní dopravy a odstavným nádražím Praha-jih.",
    "source": "https://valenta-rail.cz/vyletni-vlaky/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-DPP-DEN-HRDINU",
    "title": "Den IZS a týden hrdinů na Výstavišti Praha",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Výstaviště Praha",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "",
    "transport": "více druhů dopravy / IZS",
    "type": "prezentační akce / výstava techniky",
    "organizer": "Výstaviště Praha / složky IZS; účast DPP",
    "description": "Celodenní veřejná akce představí práci záchranných, bezpečnostních a humanitárních organizací včetně DPP. Součástí bude prohlídka techniky a interaktivní program pro děti i dospělé.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-DPO-AUTOBUSY-PORUBA",
    "title": "Autobusy v Porubě",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "09:10",
    "endTime": "15:10",
    "place": "Ostrava-Poruba",
    "city": "Ostrava",
    "region": "Moravskoslezský kraj",
    "country": "Česko",
    "route": "Řecká – Alšovo náměstí – Poruba, vozovna – Dílny DP Ostrava – Duha – Poruba, Opavská",
    "transport": "autobus",
    "type": "nostalgická jízda / výstava historických autobusů",
    "organizer": "Dopravní podnik Ostrava",
    "description": "Čtyři různé typy historických autobusů pojedou 3. 10. 2026 od 9:10 do 15:10 v 30minutovém intervalu ze zastávky Řecká přes Alšovo náměstí, vozovnu Poruba, Dílny DP Ostrava a Duhu na Porubu, Opavskou. Na konečné budou k prohlídce další dva historické autobusy ze sbírky DPO.",
    "source": "https://www.dpo.cz/aktualne/novinky.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "ajhpjbgdk3b331s9vnllid6g38",
    "title": "Praha–Lužná: historický motorový vlak do muzea ČD",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261006-DPP-MUZEUM-TRAMVAJE",
    "title": "Komentovaná prohlídka Muzea MHD – Tramvaje",
    "from": "6. 10. 2026",
    "to": "6. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Muzeum MHD, vozovna Střešovice",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "",
    "transport": "tramvaj / MHD",
    "type": "komentovaná prohlídka",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Komentovaná prohlídka tramvajové expozice Muzea MHD s vedoucím Archivu DPP Robertem Marou. Přesný čas a podmínky účasti zatím nebyly zveřejněny.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-DPP-IKARUS-RADOTIN",
    "title": "Výročí radotínských linek s Ikarusem E91",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Radotín a západní část Prahy",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Stodůlky – Nádraží Radotín / Nádraží Radotín – K Višňovce",
    "transport": "autobus",
    "type": "nostalgická jízda / výroční akce",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Jízdy autobusu Ikarus E91 připomenou 45 let od zahájení provozu linky 256 Stodůlky – Nádraží Radotín a 25 let linky 245 Nádraží Radotín – K Višňovce. Časy a podrobný program zatím nebyly zveřejněny.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "cop36dpn6hgm8b9jc5gj6b9k6dij4bb170o3cb9l71h6cdhh64r64db268",
    "title": "DOD vozovna Pankrác",
    "from": "17. 10. 2026",
    "to": "17. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "353mki17al6fgvjicso5bot6lc",
    "title": "Posázaví: Posázavský pacifik s Ventilovkou",
    "from": "17. 10. 2026",
    "to": "17. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261024-DPP-JEVANY",
    "title": "Autobusem na výlov Jevanského rybníka",
    "from": "24. 10. 2026",
    "to": "24. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Praha – Jevany",
    "city": "Praha / Jevany",
    "region": "Praha / Středočeský kraj",
    "country": "Česko",
    "route": "Praha – Jevany",
    "transport": "autobus",
    "type": "zvláštní jízda",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Zvláštní autobusová jízda z Prahy na výlov Jevanského rybníka. Vozidlo, jízdní řád, cena a podmínky účasti zatím nebyly zveřejněny.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "2i1u254qgp9ia81426t909uejl",
    "title": "Císař František Josef I. na bojišti 1866 u Hradce Králové",
    "from": "24. 10. 2026",
    "to": "24. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "rlh2hdaojnoiqvc0lai81gmr5g",
    "title": "Temelín: zvláštním vlakem k elektrárně",
    "from": "24. 10. 2026",
    "to": "24. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "088bsrn3a0gpkcnvb6nhgahnob",
    "title": "Zvláštní vlaky na Výstup na těžní věž",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "",
    "city": "",
    "region": "",
    "country": "",
    "route": "",
    "transport": "",
    "type": "",
    "organizer": "",
    "description": "",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261031-DPP-HALLOWEEN-MUZEUM",
    "title": "Halloween v Muzeu MHD",
    "from": "31. 10. 2026",
    "to": "31. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Muzeum MHD, vozovna Střešovice",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "",
    "transport": "MHD",
    "type": "muzejní akce",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Tematická halloweenská akce v Muzeu MHD ve vozovně Střešovice. Přesný čas a program zatím nebyly zveřejněny.",
    "source": "https://www.dpp.cz/spolecnost/aktuality/detail/66_3256-kalendar-akci-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-JH-UZKOKOLEJKA-DEN-ZELEZNICE",
    "title": "Jindřichohradecká úzkokolejka: Den železnice na Úzkokolejce",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Jindřichohradecké úzkokolejky",
    "city": "Jindřichův Hradec / Česká Kanada",
    "region": "Jihočeský kraj",
    "country": "Česko",
    "route": "Jindřichohradecká úzkokolejka",
    "transport": "železnice / úzkokolejka",
    "type": "den železnice / parní jízda / nostalgická akce",
    "organizer": "Jindřichohradecké úzkokolejky / Gepard Express",
    "description": "Den železnice na Jindřichohradecké úzkokolejce se uskuteční v sobotu 26. září 2026. Pořadatel uvádí, že poprvé vyrazí do akce společně na jednom vlaku obě parní lokomotivy Polka a Krausska; akce je určena fanouškům historických vlaků, fotografům i rodinám.",
    "source": "https://uzkokolejky.cz/kalendar/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260925-28-PSHZD-DOBRUSKA",
    "title": "Jízdy v Dobrušce a okolí",
    "from": "25. 9. 2026",
    "to": "28. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Dobruška a okolí",
    "city": "Dobruška",
    "region": "Královéhradecký kraj",
    "country": "Česko",
    "route": "Pardubice – Dobruška; Dobruška – Opočno pod Orlickými horami – Nové Město nad Metují; výlet do Potštejna",
    "transport": "železnice",
    "type": "nostalgické jízdy / historické motoráky",
    "organizer": "PSHŽD",
    "description": "Čtyřdenní program historických motoráků M131.1228, M131.2053 a M152.0318. V sobotu 26. 9. pendly z Dobrušky do Opočna a Nového Města nad Metují, v neděli výlet do Potštejna a 28. 9. pendly Dobruška–Opočno s návratem souprav do Pardubic a Jaroměře.",
    "source": "https://www.pshzd.cz/akce.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261002-04-PSHZD-HURVINKY-LUZNA",
    "title": "S M131.1228 na sraz Hurvínků v Lužné",
    "from": "2. 10. 2026",
    "to": "4. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "ČD Muzeum Lužná u Rakovníka",
    "city": "Lužná u Rakovníka",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "trasa bude upřesněna",
    "transport": "železnice",
    "type": "nostalgická jízda / setkání historických vozidel",
    "organizer": "PSHŽD",
    "description": "Třídenní výprava historickým motorovým vozem M131.1228 na sraz Hurvínků v Lužné. Cena 2300 Kč zahrnuje vstup do muzea; konkrétní trasa má být ještě upřesněna a účast vyžaduje rezervaci.",
    "source": "https://www.pshzd.cz/akce.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-PSHZD-LETOHRAD",
    "title": "Jízdy v Letohradu",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Letohrad",
    "city": "Letohrad",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "",
    "transport": "železnice",
    "type": "nostalgické jízdy",
    "organizer": "PSHŽD",
    "description": "PSHŽD uvádí na 3. října 2026 samostatné jízdy v Letohradu; další podrobnosti zatím na oficiální stránce nejsou zveřejněny.",
    "source": "https://www.pshzd.cz/akce.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-PSHZD-PODZIMNI-FESTIVAL",
    "title": "Podzimní pardubický festival",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "09:35",
    "endTime": "14:22",
    "place": "Pardubice centrum / Pardubice hl. n. / Rosice nad Labem",
    "city": "Pardubice",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "Pardubice centrum – Pardubice hl. n. – Pardubice-Rosice nad Labem a zpět",
    "transport": "železnice",
    "type": "dopravní festival / nostalgické jízdy",
    "organizer": "PSHŽD",
    "description": "Podzimní pardubický festival s pěti páry zvláštních vlaků mezi Pardubicemi centrem a Rosicemi nad Labem. Návrh jízdního řádu uvádí odjezdy z Pardubic centra 9:35–13:35 a návraty s příjezdy 10:22–14:22.",
    "source": "https://www.pshzd.cz/akce.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261011-PSHZD-NA-KONICKY",
    "title": "Na koníčky motoráčkem",
    "from": "11. 10. 2026",
    "to": "11. 10. 2026",
    "time": "09:08",
    "endTime": "13:38",
    "place": "Pardubice centrum – Pardubice závodiště",
    "city": "Pardubice",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "Pardubice centrum – Pardubice hl. n. – Rosice nad Labem – Pardubice závodiště a zpět",
    "transport": "železnice",
    "type": "nostalgické jízdy / zvláštní vlak",
    "organizer": "PSHŽD",
    "description": "Pět párů motoráčkových jízd z Pardubic centra na závodiště. Návrh jízdního řádu uvádí první odjezd v 9:08 a poslední návrat do Pardubic centra ve 13:38; jednotné vstupné 40 Kč, zlevněné 30 Kč.",
    "source": "https://www.pshzd.cz/akce.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-DPMB-DRAK-DOD",
    "title": "Brno: Jak se staví Drak – velký den otevřených dveří Ústředních dílen DPMB",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "13:00",
    "endTime": "17:00",
    "place": "Ústřední dílny DPMB, Hudcova 74, Medlánky",
    "city": "Brno",
    "region": "Jihomoravský kraj",
    "country": "Česko",
    "route": "linka 1 / retro tramvaje / speciální pendl vozovna – Ústřední dílny",
    "transport": "tramvaj / MHD",
    "type": "den otevřených dveří / prezentační akce / historická vozidla",
    "organizer": "Dopravní podnik města Brna",
    "description": "Velký den otevřených dveří Ústředních dílen DPMB zaměřený na výrobu a údržbu tramvají Drak. Program zahrnuje ukázky výroby a oprav tramvají, jednotlivá pracoviště dílen, komentované prohlídky, historické a retro vozy, dopravní trenažéry, drezínu, dětskou stezku a další aktivity. Ve 13:00 proběhne slavnostní zahájení a křest knihy Tramvajemi po městech Česka. Na akci bude možné přijet linkou 1, retro tramvajemi a speciálním pendlem od vozovny k dílnám.",
    "source": "https://www.dpmb.cz/jak-se-stavi-drak-prijdte-do-dilen-dpmb",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261030-DPP-MUZEUM-OTEVRENO",
    "title": "Praha: mimořádné otevření Muzea MHD",
    "from": "30. 10. 2026",
    "to": "30. 10. 2026",
    "time": "09:00",
    "endTime": "17:00",
    "place": "Muzeum MHD, Střešovice",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "",
    "transport": "MHD / technické muzeum",
    "type": "mimořádné otevření / technické muzeum",
    "organizer": "Dopravní podnik hl. m. Prahy",
    "description": "Muzeum MHD ve Střešovicích bude v pátek 30. 10. 2026 během podzimních školních prázdnin mimořádně otevřeno ve standardní době 9:00–17:00.",
    "source": "https://muzeum.dpp.cz/kalendar-akci/detail/1108_2898-stredy-18-a-25-unora-2026-v-muzeu-mhd-otevreno",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-STRASICE-SETKANI-BUSU",
    "title": "Strašice: setkání historických autobusů",
    "from": "26. 9. 2026",
    "to": "27. 9. 2026",
    "time": "10:00",
    "endTime": "17:00",
    "place": "Muzeum dopravy ve Strašicích",
    "city": "Strašice",
    "region": "Plzeňský kraj",
    "country": "Česko",
    "route": "",
    "transport": "autobus / historická vozidla / muzeum dopravy",
    "type": "setkání historických autobusů / muzejní akce",
    "organizer": "ŠKODA-BUS klub Plzeň",
    "description": "O víkendu 26.–27. 9. 2026 proběhne ve Strašicích setkání historických autobusů. Oficiální web Muzea dopravy potvrzuje otevření expozice oba dny od 10:00 do 17:00; aktuální přehled Busportalu tento termín uvádí jako Strašické setkání historických autobusů.",
    "source": "https://skodabusklub.cz/strasice/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261017-STRASICE-ZAKONCENI",
    "title": "Strašice: zakončení sezóny Muzea dopravy",
    "from": "17. 10. 2026",
    "to": "18. 10. 2026",
    "time": "10:00",
    "endTime": "17:00",
    "place": "Muzeum dopravy ve Strašicích",
    "city": "Strašice",
    "region": "Plzeňský kraj",
    "country": "Česko",
    "route": "",
    "transport": "historická vozidla / autobus / tramvaj / trolejbus / muzeum dopravy",
    "type": "zakončení sezóny / otevření muzea",
    "organizer": "ŠKODA-BUS klub Plzeň",
    "description": "Muzeum dopravy ve Strašicích uzavírá návštěvnickou sezónu o víkendu 17.–18. 10. 2026. Oficiální web potvrzuje otevření oba dny 10:00–17:00 a uvádí, že se muzeum s návštěvnickou sezónou loučí v říjnu; aktuální přehled Busportalu označuje tento víkend jako zakončení sezóny.",
    "source": "https://skodabusklub.cz/strasice/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-CD-HYDRA-TRUTNOV",
    "title": "Praha–Trutnov: nostalgická jízda s Hydrou",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "09:38",
    "endTime": "20:07",
    "place": "Praha-Vysočany / Trutnov hl. n.",
    "city": "Praha / Trutnov",
    "region": "Praha / Středočeský kraj / Královéhradecký kraj",
    "country": "Česko",
    "route": "Praha-Vysočany – Nymburk – Poděbrady – Chlumec nad Cidlinou – Nový Bydžov – Stará Paka – Martinice v Krkonoších – Kunčice nad Labem – Trutnov hl. n. a zpět",
    "transport": "železnice / motorový vlak",
    "type": "nostalgická jízda / zvláštní vlak",
    "organizer": "České dráhy (dle zveřejněného sekundárního zdroje)",
    "description": "Zveřejněná informace uvádí nostalgickou jízdu motorovým vozem řady 854 „Hydra“ do Trutnova. Z Prahy-Vysočan má vlak R90763 odjet v 9:38 a do Trutnova přijet ve 13:23; zpět má vlak R90764 odjet v 16:38 a do Prahy-Vysočan přijet ve 20:07.",
    "source": "https://www.hravestroje.cz/kalendar-dopravnich-akci/nostalgicka-jizda-hydra-trutnov/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-JH-PONORKY-LOUCENI",
    "title": "Jindřichohradecká úzkokolejka: Loučení s ponorkami",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "14:10",
    "endTime": "00:13",
    "place": "Jindřichův Hradec / Černovice u Tábora",
    "city": "Jindřichův Hradec / Černovice",
    "region": "Jihočeský kraj",
    "country": "Česko",
    "route": "Jindřichův Hradec – Kamenice nad Lipou – Černovice a zpět",
    "transport": "železnice / motorový vůz",
    "type": "rozlučková nostalgická jízda / festival / historické vozidlo",
    "organizer": "Jindřichohradecké úzkokolejky",
    "description": "Rozlučkové jízdy motorových vozů řady M27 „ponorka“ 26. 9. 2026. První jízda odjíždí z Jindřichova Hradce ve 14:10, do Černovic přijíždí v 15:45; další jízdy pokračují odpoledne a večer a poslední spoj odjíždí z Černovic ve 23:00 s příjezdem do Jindřichova Hradce v 0:13. V Černovicích proběhne slavnostní loučení, prohlídka města, koncerty a táborák. Pořadatel akci označuje jako poslední „plavbu“ ponorek před plánovaným přesunem vozů do nového působiště.",
    "source": "https://uzkokolejky.cz/kalendar/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-VM-140",
    "title": "Velké Meziříčí: 140 let trati do Studence",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Železniční stanice Velké Meziříčí",
    "city": "Velké Meziříčí",
    "region": "Kraj Vysočina",
    "country": "Česko",
    "route": "Velké Meziříčí – Studenec a zpět",
    "transport": "parní vlak / drezína / železnice",
    "type": "výroční železniční slavnost / historická vozidla",
    "organizer": "Město Velké Meziříčí a partneři",
    "description": "Celodenní oslavy 140 let trati. Parní vlak s lokomotivou 555.129 do Studence a zpět (odjezdy z Velkého Meziříčí 9:40 a 13:40), historická drezína Tatra, výstava lokomotiv a traťových mechanismů a Slovenská strela.",
    "source": "https://www.velkemezirici.cz/udalosti/zabavne-odpoledne/172839-140-let-trati-velke-mezirici-studenec",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-JEMNICE-130",
    "title": "Jemnice: 130 let Jemnické dráhy",
    "from": "26. 9. 2026",
    "to": "27. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Jemnice / Moravské Budějovice",
    "city": "Jemnice / Moravské Budějovice",
    "region": "Kraj Vysočina",
    "country": "Česko",
    "route": "Moravské Budějovice – Jemnice; Jemnice – Třebelovice",
    "transport": "parní vlak / železnice",
    "type": "výroční železniční slavnost / nostalgické jízdy",
    "organizer": "SVD-JZM / partneři",
    "description": "Oslavy 130 let Jemnické dráhy 26.–27. 9. 2026. Jízdy parního vlaku a doprovodný program na nádražích v Jemnici a Moravských Budějovicích; součástí jsou také tematické prohlídky v Muzeu Jemnicka.",
    "source": "https://www.svd-jzm.cz/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-CD-RDZ-BOHUMIN",
    "title": "Bohumín: Regionální den železnice 2026",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Bohumín",
    "city": "Bohumín",
    "region": "Moravskoslezský kraj",
    "country": "Česko",
    "route": "",
    "transport": "železnice / historický vlak",
    "type": "Regionální den železnice",
    "organizer": "České dráhy",
    "description": "Regionální den železnice v Bohumíně 3. 10. 2026. Termín je potvrzen oficiálním kalendářem Dne železnice; podrobnosti programu budou doplňovány.",
    "source": "https://denzeleznice.cz/rdz-2026",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-MESTEC-PARNI",
    "title": "Městec Králové: parní víkend",
    "from": "3. 10. 2026",
    "to": "4. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Dymokury / Městec Králové / Nový Bydžov",
    "city": "Městec Králové",
    "region": "Středočeský / Královéhradecký kraj",
    "country": "Česko",
    "route": "Dymokury – Městec Králové – Nový Bydžov a zpět",
    "transport": "parní vlak / železnice",
    "type": "nostalgické jízdy / parní víkend",
    "organizer": "",
    "description": "Parní víkend 3.–4. 10. 2026 na trase Dymokury–Městec Králové–Nový Bydžov a zpět. Souhrnný kalendář uvádí lokomotivu 310.0134 „Babička“.",
    "source": "https://tyburcovo.nafoceno.cz/NOSTALGICKE-VLAKY-Kalendar-jizd.html",
    "verification": "PŘEDBĚŽNÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261017-ROZNOV-EXPRES",
    "title": "Valašské Meziříčí–Rožnov: Rožnovský expres",
    "from": "17. 10. 2026",
    "to": "17. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Valašské Meziříčí / Rožnov pod Radhoštěm",
    "city": "Rožnov pod Radhoštěm",
    "region": "Zlínský kraj",
    "country": "Česko",
    "route": "Valašské Meziříčí – Rožnov pod Radhoštěm a zpět",
    "transport": "parní vlak / železnice",
    "type": "nostalgická jízda",
    "organizer": "Nadační fond Svět železnice / partneři",
    "description": "Rožnovský expres 17. 10. 2026. Souhrnný kalendář uvádí parní lokomotivu 423.041 „Velký bejček“; smlouva města potvrzuje zajištění historických vlaků pro rok 2026.",
    "source": "https://tyburcovo.nafoceno.cz/NOSTALGICKE-VLAKY-Kalendar-jizd.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261017-RDZ-LIBEREC",
    "title": "Liberec: Regionální den železnice",
    "from": "17. 10. 2026",
    "to": "17. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Liberec",
    "city": "Liberec",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "",
    "transport": "parní vlak / železnice",
    "type": "Regionální den železnice",
    "organizer": "České dráhy / Kolej-klub",
    "description": "Regionální den železnice v Liberci; zvláštní vlaky v okolí Liberce a jízdy do dopravních podniků. Kolej-klub uvádí vozidla M 152.0469, M 152.0604 a T 334.0866.",
    "source": "https://tyburcovo.nafoceno.cz/NOSTALGICKE-VLAKY-Kalendar-jizd.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-JH-REPUBLIKA",
    "title": "Jindřichohradecká úzkokolejka: Republika přijíždí Úzkokolejkou",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "09:50",
    "endTime": "18:05",
    "place": "Jindřichův Hradec / Nová Bystřice",
    "city": "Jindřichův Hradec / Nová Bystřice",
    "region": "Jihočeský kraj",
    "country": "Česko",
    "route": "Jindřichův Hradec – Nová Bystřice a zpět",
    "transport": "železnice / parní vlak / úzkokolejka",
    "type": "tematická nostalgická jízda / historická akce",
    "organizer": "Jindřichohradecké úzkokolejky",
    "description": "Tematická parní jízda 28. 10. 2026 do Nové Bystřice k výročí vzniku Československa. Program je stylizovaný do roku 1918 a zahrnuje dobovou atmosféru, hudbu a program pro rodiny. Zveřejněný jízdní řád uvádí odjezd z Jindřichova Hradce v 9:50, příjezd do Nové Bystřice ve 12:58, odjezd zpět v 15:35 a návrat do Jindřichova Hradce v 18:05.",
    "source": "https://uzkokolejky.cz/kalendar/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-DPP-KZC-KACEROV-ECS",
    "title": "Praha: zážitková turistika KŽC + Depo Kačerov a trasa C s Ečs",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "09:00; 14:00",
    "endTime": "",
    "place": "Praha-Vysočany / Depo Kačerov / trasa C",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Praha-Vysočany – Depo Kačerov; následně trasa C metra",
    "transport": "železnice / metro / historická vozidla",
    "type": "zážitková jízda / prohlídka depa",
    "organizer": "Dopravní podnik hl. m. Prahy / KŽC Doprava",
    "description": "Speciální zážitková turistika DPP a KŽC dne 10. 10. 2026. Začíná na nádraží Praha-Vysočany jízdou vlaku KŽC vedeného lokomotivou řady 749 s historickými vozy, pokračuje návštěvou Depa Kačerov s fotopříležitostí a jízdou historickou soupravou metra Ečs na trase C. Oficiální Fanshop DPP nabízí dva turnusy s orientačním odjezdem kolem 9:00 a 14:00; cena 890 Kč.",
    "source": "https://fanshop.dpp.cz/zazitkova-turistika-s-kzc-749-historicke-vozy-depo-kacerov-a-trasa-c-ecs/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-ZUBACKA-BRAMBOROVA",
    "title": "Kořenov: Bramborová sobota na Zubačce",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Kořenov / Zubačka",
    "city": "Kořenov",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "Tanvald – Kořenov – Harrachov",
    "transport": "historická železnice / historický autobus",
    "type": "tematický den / nostalgické jízdy",
    "organizer": "Železniční společnost Tanvald",
    "description": "Bramborová sobota s jízdami ozubnicové lokomotivy, muzeem, výtopnou, důlní železnicí a historickým autobusem Liberec–Kořenov–Jizerka.",
    "source": "https://www.zubacka.cz/index.php?catid=7&id=717%3Abramborova-sobota-na-zubacce-26-09-2026&view=article",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260927-ZUBACKA-IQLANDIA",
    "title": "Kořenov–Liberec: Vlakem do iQLANDIE a Babylonu",
    "from": "27. 9. 2026",
    "to": "27. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Kořenov / Liberec",
    "city": "Liberec",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "Kořenov – Liberec a zpět",
    "transport": "historický vlak",
    "type": "zážitková / výletní jízda",
    "organizer": "Železniční společnost Tanvald",
    "description": "Zvláštní historický vlak z Kořenova do Liberce za iQLANDIÍ a Centrem Babylon; možnost návštěvy muzea a výtopny v Kořenově.",
    "source": "https://www.zubacka.cz/index.php?catid=7&id=718%3Avlakem-do-iqlandie-a-babylonu-27-09-2026&view=article",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-SAFARI-EXPRESS",
    "title": "Safari Park Express do Dvora Králové",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Dvůr Králové nad Labem / Safari Park",
    "city": "Dvůr Králové nad Labem",
    "region": "Královéhradecký kraj",
    "country": "Česko",
    "route": "Kolín / střední a severovýchodní Čechy – Dvůr Králové nad Labem a zpět",
    "transport": "retro vlak / návazný autobus",
    "type": "zážitková / výletní jízda",
    "organizer": "H&H železniční společnost",
    "description": "Speciální retro vlak do Safari Parku včetně svozového autobusu a vstupu do pěší části safari; přesnou nástupní trasu je vhodné před cestou ověřit u pořadatele.",
    "source": "https://safaripark.cz/cz/zazitky/safari-express",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260928-POZNEJ-VLTAVU-EXPRES",
    "title": "Praha: Poznej Vltavu – Festivalový expres",
    "from": "28. 9. 2026",
    "to": "28. 9. 2026",
    "time": "10:00",
    "endTime": "17:00",
    "place": "Vltava – Holešovice / Trojská kotlina",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Port7 – Libeň – Stará čistírna Bubeneč – Císařský ostrov – Port7",
    "transport": "loď / historický autobus (výstava)",
    "type": "festival / zvláštní doprava",
    "organizer": "PID / organizátoři festivalu Poznej Vltavu",
    "description": "Bezplatná speciální lodní linka po 45 minutách; součástí programu PID je také výstava 30 let přestupního tarifu v historickém autobusu Karosa B732.",
    "source": "https://pid.cz/pozvanka-na-prodlouzeny-vikend-s-pid-den-hrdinu-a-poznej-vltavu/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260928-ZASMUKY-ZAHRADNI",
    "title": "Horní Chvatliny: poslední provozní den Zahradní železnice Zásmucka",
    "from": "28. 9. 2026",
    "to": "28. 9. 2026",
    "time": "10:00",
    "endTime": "16:00",
    "place": "Zahradní železnice Zásmucka, Horní Chvatliny",
    "city": "Dolní Chvatliny",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "",
    "transport": "zahradní železnice",
    "type": "provozní den / ukončení sezony",
    "organizer": "Zahradní železnice Zásmucka",
    "description": "Poslední pravidelný provozní den sezony zahradní železnice o rozchodu 300 mm; dobrovolné vstupné.",
    "source": "https://kolin.cz/akce/2026-09-28/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-MAYRAU-POLDI",
    "title": "Vinařice: poslední jízda Poldi vlaku v Mayrau",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "10:30",
    "endTime": "16:40",
    "place": "Hornický skanzen Mayrau",
    "city": "Vinařice",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "okruh Poldi dráhy v areálu Mayrau",
    "transport": "průmyslová úzkokolejka",
    "type": "provozní den / ukončení sezony",
    "organizer": "Hornický skanzen Mayrau",
    "description": "Poslední letošní jízdy Poldi vlaku na 800mm dráze; odjezdy každou hodinu 10:30–16:30.",
    "source": "https://www.hravestroje.cz/kalendar-dopravnich-akci/posledni-jizda-poldi-vlaku-mayrau/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260926-BRASY-PAROSTROJNI",
    "title": "Břasy: jízdy Parostrojní železnice",
    "from": "26. 9. 2026",
    "to": "26. 9. 2026",
    "time": "13:00",
    "endTime": "17:00",
    "place": "Parostrojní železnice Břasy",
    "city": "Břasy",
    "region": "Plzeňský kraj",
    "country": "Česko",
    "route": "",
    "transport": "zahradní / parková železnice",
    "type": "veřejné jízdy",
    "organizer": "Parostrojní železnice Břasy",
    "description": "Veřejné jízdy na zahradní železnici o rozchodu 7¼ palce, vyhlášené na odpoledne 26. září.",
    "source": "https://www.hravestroje.cz/kalendar-dopravnich-akci/jizdy-parostrojni-zeleznice-brasy/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-LETOHRAD-PARNI-SOBOTA",
    "title": "Letohrad: Podorlická parní sobota 2026",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "09:00",
    "endTime": "16:00",
    "place": "železniční depo Letohrad",
    "city": "Letohrad",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "Letohrad a okolní tratě – Jablonné n. O., Žamberk, Litice n. O., Ústí n. O., Dolní Lipka aj.",
    "transport": "parní a historická železnice",
    "type": "železniční slavnost / zvláštní jízdy",
    "organizer": "Výtopna Dolní Lipka / Muzeum starých strojů a technologií",
    "description": "Velká parní akce s 12 historickými stroji; sedm strojů v provozu. Součástí je návrat parního motorového vozu M 124.001 Komarek, přehlídka lokomotiv, drezína a historický jídelní vůz.",
    "source": "https://vytopnadolnilipka.cz/podorlicka-parni-sobota",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-PRAHA-ARCHITRAM-BROWNFIELDY",
    "title": "Praha: CAMP Tour – tramvají mezi brownfieldy",
    "from": "3. 10. 2026",
    "to": "3. 10. 2026",
    "time": "14:00",
    "endTime": "17:00",
    "place": "Karlínské náměstí, zastávka směr Křižíkova",
    "city": "Praha",
    "region": "Praha",
    "country": "Česko",
    "route": "Karlínské náměstí – transformační území Prahy – Karlínské náměstí",
    "transport": "historická tramvaj",
    "type": "komentovaná jízda",
    "organizer": "CAMP / IPR Praha / Den architektury",
    "description": "Dvě přibližně 90minutové komentované jízdy tramvají Architram 9219 v 14:00 a 15:30 s Jiřím Jarošem z IPR; zaměření na pražská transformační území a brownfieldy. Nutná rezervace.",
    "source": "https://www.denarchitektury.cz/program/praha-camp-tour-tramvaji-mezi-brownfieldy/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-MPZ-ZBYSOV-PODZIMNI",
    "title": "Zbýšov: podzimní parní jízda Muzea průmyslových železnic",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "10:15",
    "endTime": "17:05",
    "place": "Muzeum průmyslových železnic, Zbýšov – Důl Jindřich",
    "city": "Zbýšov",
    "region": "Jihomoravský kraj",
    "country": "Česko",
    "route": "Zbýšov-Důl Jindřich – Zastávka u Brna a zpět",
    "transport": "průmyslová úzkokolejka / parní vlak",
    "type": "mimořádná podzimní jízda",
    "organizer": "Muzeum průmyslových železnic",
    "description": "Mimořádná podzimní náhrada za srpnové parní jízdy zrušené kvůli suchu. V provozu mají být obě parní lokomotivy BS 80 a Henschel a také důlní vlak; zveřejněno osm odjezdů mezi 10:15 a 16:10.",
    "source": "https://www.mpz.cz/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-IDSJMK-MUTENICE",
    "title": "Mutěnice: mimořádné vlaky k Burčákovému pochodu",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Mutěnice a okolí",
    "city": "Mutěnice",
    "region": "Jihomoravský kraj",
    "country": "Česko",
    "route": "Brno – Zaječí – Mutěnice; Hodonín – Mutěnice a zpět",
    "transport": "mimořádné a posílené vlaky",
    "type": "zvláštní doprava k akci",
    "organizer": "IDS JMK",
    "description": "Mimořádné vlaky a posílená doprava k Putování slováckým vinohradem.",
    "source": "https://www.idsjmk.cz/lockouts/detail/4586",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-11-ZITTAU-REICHSBAHN",
    "title": "Žitava: historická souprava Reichsbahn na úzkokolejce",
    "from": "10. 10. 2026",
    "to": "11. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Žitavská úzkokolejka",
    "city": "Žitava",
    "region": "Sasko",
    "country": "Německo",
    "route": "Zittau – Bertsdorf – Oybin / Jonsdorf",
    "transport": "úzkokolejka / historický vlak",
    "type": "historický provoz",
    "organizer": "Sächsisch-Oberlausitzer Eisenbahngesellschaft",
    "description": "Víkendový provoz historické soupravy Reichsbahn a posilových vlaků.",
    "source": "https://www.parnizaziteksasko.cz/cz/akce/l19_Zittauer_Schmalspurbahn.html",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-11-MUSKAU-WALDEISENBAHN",
    "title": "Mužakov: podzimní jízdy lesní železnice",
    "from": "10. 10. 2026",
    "to": "11. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Waldeisenbahn Muskau",
    "city": "Weißwasser / Bad Muskau",
    "region": "Sasko",
    "country": "Německo",
    "route": "Weißwasser – Bad Muskau / Kromlau",
    "transport": "úzkokolejná lesní železnice",
    "type": "podzimní jízdy",
    "organizer": "Waldeisenbahn Muskau",
    "description": "Víkendové podzimní jízdy lesní železnice s dieselovou lokomotivou.",
    "source": "https://www.parnizaziteksasko.cz/cz/akce/month_2026-10",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261024-SEIDELUV-VLAK",
    "title": "České Budějovice–Horní Planá: Seidelův vlak",
    "from": "24. 10. 2026",
    "to": "24. 10. 2026",
    "time": "07:45",
    "endTime": "18:00",
    "place": "České Budějovice – Český Krumlov – Horní Planá",
    "city": "Horní Planá",
    "region": "Jihočeský kraj",
    "country": "Česko",
    "route": "České Budějovice – Český Krumlov – Horní Planá a zpět",
    "transport": "zvláštní vlak",
    "type": "tematická historická jízda",
    "organizer": "Museum Fotoateliér Seidel / České dráhy",
    "description": "Seidelův vlak ke Stifterovu dni. Ve vlaku ukázky dobových snímků, v Horní Plané historický a kulturní program. Odjezd České Budějovice 7:45, návrat 18:00.",
    "source": "https://www.seidel.cz/cz/seideluv-vlak-2026/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-MAYRAU-DEN-STC-KRAJE",
    "title": "Vinařice: Den Středočeského kraje – historická vozidla a vlaky na Mayrovce",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "10:00",
    "endTime": "14:00",
    "place": "Hornický skanzen Mayrau",
    "city": "Vinařice",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "Kladno – Mayrau a zpět; důlní a Poldi úzkorozchodná dráha",
    "transport": "historický vlak / úzkokolejky / historická vozidla",
    "type": "Den Středočeského kraje",
    "organizer": "Hornický skanzen Mayrau",
    "description": "Přehlídka historických vozidel, komentované prohlídky a nově jízdy na obou úzkorozchodných drahách. Z Kladna má být vypraven motorový vůz řady 810 na Mayrovku a zpět.",
    "source": "https://dul-mayrau.cz/uncategorized/den-stredoceskeho-kraje-historicka-vozidla-na-mayrovce-28-rijna-2026/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-CHrustenice-VLACEK",
    "title": "Chrustenice: sváteční jízdy důlním vláčkem a Hagenovy pověsti",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "10:00",
    "endTime": "16:00",
    "place": "Chrustenická šachta",
    "city": "Chrustenice",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "cca 1 km podzemím Chrustenické šachty",
    "transport": "důlní železnice",
    "type": "mimořádné otevření / jízdy vláčkem",
    "organizer": "Chrustenická šachta",
    "description": "Mimořádné sváteční otevření. Jízdy důlním vláčkem přibližně každých 30 minut, některé spojené se scénickým čtením Hagenových pověstí; prohlídky funkční techniky.",
    "source": "https://infocentrumberoun.cz/kalendar/12449",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-ZUBACKA-RAKUSANKA",
    "title": "Tanvald / Kořenov: Rakušanka na Zubačce",
    "from": "28. 10. 2026",
    "to": "28. 12. 2026",
    "time": "",
    "endTime": "",
    "place": "Tanvald – Kořenov – Harrachov",
    "city": "Kořenov",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "Tanvald – Kořenov – Harrachov a zpět",
    "transport": "historický vlak / ozubnicová železnice",
    "type": "jízdy s ozubnicovou lokomotivou",
    "organizer": "Spolek Zubačka",
    "description": "Sváteční jízdy s unikátní ozubnicovou lokomotivou T 426.0 Rakušanka na nejstrmější železniční trati v ČR.",
    "source": "https://w.zubacka.cz/index.php/jizdy-zvlastnich-vlaku/jizdy-s-ozubnicovou-lokomotivou",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-LIBEREC-HIST-TRAM",
    "title": "Liberec: sváteční jízdy historických tramvají",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Liberec",
    "city": "Liberec",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "",
    "transport": "historická tramvaj",
    "type": "sváteční nostalgické jízdy",
    "organizer": "Boveraclub / DPMLJ",
    "description": "Tradiční jízdy historických tramvají v Liberci ke státnímu svátku 28. října.",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261031-SOLVAY-UKONCENI",
    "title": "Svatý Jan pod Skalou: ukončení sezóny Solvayových lomů",
    "from": "31. 10. 2026",
    "to": "31. 10. 2026",
    "time": "",
    "endTime": "",
    "place": "Skanzen Solvayovy lomy",
    "city": "Svatý Jan pod Skalou",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "",
    "transport": "úzkorozchodná železnice / skanzen",
    "type": "ukončení sezóny",
    "organizer": "Společnost Barbora / Solvayovy lomy",
    "description": "Slavnostní ukončení sezóny s kavalkádou vlaků všech provozních lokomotiv a parním provozem lokomotivy Bronhilda.",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261031-HALLOWEEN-MOTORACEK",
    "title": "Pardubice–Chrast: Halloweenský motoráček – Tajemství dýňové lucerny",
    "from": "31. 10. 2026",
    "to": "31. 10. 2026",
    "time": "15:59",
    "endTime": "19:47",
    "place": "Pardubice centrum – Chrast u Chrudimi",
    "city": "Pardubice / Chrast u Chrudimi",
    "region": "Pardubický kraj",
    "country": "Česko",
    "route": "Pardubice centrum – Pardubice hl.n. – Rosice n. L. – Chrudim – Slatiňany – Chrast u Chrudimi a zpět",
    "transport": "historický vlak / motoráček",
    "type": "tematická nostalgická jízda",
    "organizer": "Pardubický spolek historie železniční dopravy / M131 Zážitky",
    "description": "Historický motoráček M131.1133 + BDLm + M131.1228 z Pardubic do Chrasti u Chrudimi. V cíli halloweenský program a strašidelná stezka.",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261017-SVESTKOVA-CHARITA",
    "title": "Teplice–Libčeves: charitativní jízda po Švestkové dráze",
    "from": "17. 10. 2026",
    "to": "17. 10. 2026",
    "time": "15:00",
    "endTime": "",
    "place": "Teplice hl. n. / Libčeves",
    "city": "Teplice",
    "region": "Ústecký kraj",
    "country": "Česko",
    "route": "Teplice hl. n. – Švestková dráha – Libčeves a zpět",
    "transport": "železnice / zvláštní vlak",
    "type": "charitativní jízda",
    "organizer": "Správa Ústecké dráhy / partneři",
    "description": "Charitativní jízda po Švestkové dráze s návštěvou Palírny AŽD v Libčevsi. Výtěžek z jízdného je určen na podporu výstavby nového útulku Anidef.",
    "source": "",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260928-TOVACOV-SVATOVACLAV",
    "title": "Tovačov: svatováclavské jízdy historického motoráčku",
    "from": "28. 9. 2026",
    "to": "28. 9. 2026",
    "time": "",
    "endTime": "",
    "place": "Kroměříž – Kojetín – Tovačov",
    "city": "Tovačov",
    "region": "Olomoucký / Zlínský kraj",
    "country": "Česko",
    "route": "Kroměříž – Kojetín – Tovačov",
    "transport": "historický motorový vlak",
    "type": "zvláštní nostalgické jízdy",
    "organizer": "Kroměřížská dráha / Místní dráha Kojetín–Tovačov",
    "description": "Bonusové svatováclavské jízdy Hanáckého léta na kolejích. M152.0 s přípojným vozem Baafx podle letního jízdního řádu.",
    "source": "https://kolmix.cz/tovacovka/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-04-ORACOV-MODELY",
    "title": "Oráčov: modelářské setkání",
    "from": "3. 10. 2026",
    "to": "4. 10. 2026",
    "time": "09:00",
    "endTime": "16:00",
    "place": "Oráčov",
    "city": "Oráčov",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "",
    "transport": "železniční modelářství",
    "type": "výstava / modelářské setkání",
    "organizer": "Modeláři místní dráhy Rakovník–Mladotice / obec Oráčov",
    "description": "První ročník modelářského setkání: kolejiště H0, lesní železnice H0e, moduly TT a zahájení provozu na novém depu.",
    "source": "https://www.hravestroje.cz/kalendar-dopravnich-akci/modelarske-setkani-oracov/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-SOLVAY-NOCNI",
    "title": "Solvayovy lomy: noční parní jízdy a prohlídky",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "19:00",
    "endTime": "23:00",
    "place": "Skanzen Solvayovy lomy",
    "city": "Svatý Jan pod Skalou",
    "region": "Středočeský kraj",
    "country": "Česko",
    "route": "",
    "transport": "úzkokolejka / parní vlak",
    "type": "noční prohlídky / zvláštní jízdy",
    "organizer": "Společnost Barbora / Skanzen Solvayovy lomy",
    "description": "Noční prohlídky skanzenu s parními jízdami lokomotivy Bronhilda. První noční jízda začíná v 19:00.",
    "source": "https://www.solvayovylomy.cz/akce/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20260927-LIBEREC-KAROSA-B831",
    "title": "Liberec: okružní jízdy historickou Karosou B 831",
    "from": "27. 9. 2026",
    "to": "27. 9. 2026",
    "time": "13:00",
    "endTime": "16:00",
    "place": "Technické muzeum Liberec",
    "city": "Liberec",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "okružní jízdy z Technického muzea Liberec",
    "transport": "historický autobus",
    "type": "zvláštní nostalgické jízdy",
    "organizer": "Boveraclub / Technické muzeum Liberec",
    "description": "Tři okružní jízdy historickým autobusem Karosa B 831; odjezdy z nádvoří muzea ve 13:00, 14:00 a 15:00.",
    "source": "https://www.tmliberec.cz/novinky/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-JABLONEC-MALODRAHA",
    "title": "Jablonec nad Nisou: Jablonecká malodráha v událostech",
    "from": "10. 10. 2026",
    "to": "10. 10. 2026",
    "time": "09:00",
    "endTime": "15:00",
    "place": "Pražská u Remíze",
    "city": "Jablonec nad Nisou",
    "region": "Liberecký kraj",
    "country": "Česko",
    "route": "okružní jízdy po Jablonci",
    "transport": "historický autobus / tramvajová historie",
    "type": "historická jízda / exkurze",
    "organizer": "Kultura Jablonec / Boveraclub / BusLine",
    "description": "Exkurze do bývalé tramvajové vozovny U Remíze a dvě jízdy historickým autobusem RTO po Jablonci.",
    "source": "https://www.kulturajablonec.cz/akce/jablonecka-malodraha-v-udalostech/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261028-ZACLER-ZVLASTNI",
    "title": "Žacléř: zvláštním vlakem do Žacléře",
    "from": "28. 10. 2026",
    "to": "28. 10. 2026",
    "time": "09:10",
    "endTime": "17:18",
    "place": "Žacléř / Královec",
    "city": "Žacléř",
    "region": "Královéhradecký kraj",
    "country": "Česko",
    "route": "Trutnov – Královec – Žacléř",
    "transport": "historický vlak",
    "type": "zvláštní jízda",
    "organizer": "Kolej-klub / Turistická železnice Žacléř",
    "description": "Zvláštní vlaky mezi Trutnovem, Královcem a Žacléřem podle zveřejněného jízdního řádu.",
    "source": "https://zeleznicezacler.cz/akce/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261010-11-RAJNOCH-PODZIM",
    "title": "Rajnochovice: Podzimní poježdění lesní železnice",
    "from": "10. 10. 2026",
    "to": "11. 10. 2026",
    "time": "09:00",
    "endTime": "17:00",
    "place": "Rajnochovická lesní železnice",
    "city": "Rajnochovice",
    "region": "Zlínský kraj",
    "country": "Česko",
    "route": "",
    "transport": "úzkokolejka",
    "type": "zvláštní jízdy",
    "organizer": "Společnost pro obnovu Rajnochovické lesní železnice",
    "description": "Podzimní poježdění historického vláčku.",
    "source": "https://www.rajnochovicka.cz/aktuality",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  },
  {
    "id": "DA-20261003-04-BRNO-OLYMPIA-PARA",
    "title": "Brno: parní provozní víkend Parkové dráhy Olympia",
    "from": "3. 10. 2026",
    "to": "4. 10. 2026",
    "time": "10:00",
    "endTime": "18:00",
    "place": "Olympia park",
    "city": "Brno",
    "region": "Jihomoravský kraj",
    "country": "Česko",
    "route": "",
    "transport": "parková železnice",
    "type": "parní jízdy",
    "organizer": "S.M.P.D. / Parková dráha Brno",
    "description": "Parní provozní víkend.",
    "source": "https://www.smpd.cz/",
    "verification": "POTVRZENÁ",
    "status": "PLÁNOVANÁ"
  }
];
